project_id = "mttpdwowikfzcdpehlrd"

[functions.pay-video-stream]
verify_jwt = false

[functions.get-video-stream]
verify_jwt = false

[functions.get-stream]
verify_jwt = false

[functions.pay-stream]
verify_jwt = false

[functions.artist-stats]
verify_jwt = false

[functions.generate-covers]
verify_jwt = false

[functions.request-play]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
